### PR TITLE
Debug creating a new score set fail if users choose superseded score set

### PR DESCRIPTION
**Pull request by EstelleDa**

### CODE REVIEW

**Comment by bencap** [comment]
I made a mistake with the release branch, so merged the main branch into this one and force pushed so that we were up to date.

**Review by bencap — APPROVED** [review]
Thanks for taking care of this @EstelleDa, looks good. I'm going to make a change for this on the backend as well (unless you would like to) so we can make sure API users don't also encounter this.

**Comment by bencap** [comment]
Gotcha thanks for looking, the validation error is probably sufficient. I'll deploy this tomorrow AM so that the user who is blocked by it is able to continue.

**Comment by EstelleDa** [comment]
Thanks Ben! I'll let him know.

**Pull request merged**
