### PR TITLE
Rename hgvs router to transcripts

### PR DESCRIPTION
**Pull request by EstelleDa**
Front end codes of https://github.com/VariantEffect/mavedb-api/issues/331

### CODE REVIEW

**Review by bencap — APPROVED** [review]

**Comment by bencap** [comment]
Oops my bad Estelle, I'm going to revert this so we can merge it into 2024.4.4. I already merged 2024.4.3 in but must have missed this PR.

**Comment by EstelleDa** [comment]
lol~ No worries! Then I merged this to 2024.4.4.

**Comment by EstelleDa** [comment]
@bencap I checked 2024.4.4, this branch has been merged already.

**Comment by bencap** [comment]
Yeah, I fixed the merge this morning :)

**Pull request merged**
